In [165]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split

In [166]:
#mason df_cleaned is declared to the cleaned dataset from the Midterm

df_cleaned = pd.read_csv('cleaned_hotel_bookings.csv')

In [167]:
#mason check initial dataset before Split

df_cleaned.head(1)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,total_of_special_requests,reservation_status,reservation_status_date,month,total_guests,stay_duration,is_family,arrival_date,arrival_month_num,is_weekend_arrival
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,Check-Out,00:00.0,1,2,0,0,7/1/2015,7,0

In [168]:
#mason shape of dataset before Split

df_cleaned.shape

(119390, 37)

In [169]:
#mason Split dataset into 70 train/30 temp

train_df, temp_df = train_test_split(df_cleaned, test_size=0.3, random_state=42)

In [170]:
#mason Splitting temp_df into validation_df and test_df so its 15/15

validation_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)

In [171]:
#mason checking shape of new Splits comapred to total shape to ensure 70/15/15 proportion of Split is correct

print("-- Shape of New Splits --")
print()
print()
print("-Total Dataset Before Split (100%):")
print(df_cleaned.shape)
print()
print("-Train Split (70%):")
print(train_df.shape)
print()
print("-Validation Split (15%):")
print(validation_df.shape)
print()
print("-Test Split (15%):")
print(test_df.shape)
print()

-- Shape of New Splits --


-Total Dataset Before Split (100%):
(119390, 37)

-Train Split (70%):
(83573, 37)

-Validation Split (15%):
(17908, 37)

-Test Split (15%):
(17909, 37)

In [172]:
#mason download the Splits to .csv format for later use

train_df.to_csv("Train.csv", index=False)
validation_df.to_csv("Validation.csv", index=False)
test_df.to_csv("Test.csv", index=False)

In [173]:
#mason confirmed downloaded files

!ls -1

cleaned_hotel_bookings.csv
sample_data
Test.csv
Train.csv
Validation.csv

In [174]:

###############   LINEAR REGRESSION or LOGISTIC REGRESSION  ####################

In [175]:
#mason ############# use train.csv(declared as df_train) from this point (im pretty sure) and not cleaned_hotel_bookings.csv

In [176]:
#mason declare df_train to read the .csv sheet we downloaded earlier

df_train = pd.read_csv('Train.csv')

In [177]:
#mason shape of train dataset
df_train.shape

(83573, 37)

In [178]:
#mason inspect train dataset to see what we're working with
df_train.head(4)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,total_of_special_requests,reservation_status,reservation_status_date,month,total_guests,stay_duration,is_family,arrival_date,arrival_month_num,is_weekend_arrival
0,Resort Hotel,1,122,2016,December,53,27,0,4,2,...,2,Canceled,00:00.0,1,2,4,0,12/27/2016,12,0
1,City Hotel,1,20,2015,July,30,22,0,2,2,...,0,Canceled,00:00.0,1,2,2,0,7/22/2015,7,0
2,City Hotel,0,87,2017,April,16,16,2,3,3,...,0,Check-Out,00:00.0,1,3,5,1,4/16/2017,4,1
3,Resort Hotel,0,0,2017,February,5,2,0,1,1,...,1,Check-Out,00:00.0,1,1,1,0,2/2/2017,2,0

In [179]:
# starting regression with train dataset